export const moviesArr = [
  {
    "id":"1",
    "link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJD2B8pKHHWNkwyixPxPhKHAWxzXbNYaBkA&usqp=CAU",
    "name": "33 слова о дизайне",
    "isLiked": true,
    "duration": "1ч 47м",
  },
  {
    "id":"2",
    "link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJD2B8pKHHWNkwyixPxPhKHAWxzXbNYaBkA&usqp=CAU",
    "name": "Киноальманах «100 лет дизайна»",
    "isLiked": false,
    "duration": "1ч 3м",
  },
  {
    "id":"3",
    "link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJD2B8pKHHWNkwyixPxPhKHAWxzXbNYaBkA&usqp=CAU",
    "name": "В погоне за Бенкси",
    "isLiked": false,
    "duration": "1ч 42м",
  },
  {
    "id":"4",
    "link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJD2B8pKHHWNkwyixPxPhKHAWxzXbNYaBkA&usqp=CAU",
    "name": "Баския: Взрыв реальности",
    "isLiked": false,
    "duration": "1ч 21м",
  },
  {
    "id":"5",
    "link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJD2B8pKHHWNkwyixPxPhKHAWxzXbNYaBkA&usqp=CAU",
    "name": "Бег это свобода",
    "isLiked": false,
    "duration": "1ч 44м",
  },
  {
    "id":"6",
    "link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJD2B8pKHHWNkwyixPxPhKHAWxzXbNYaBkA&usqp=CAU",
    "name": "Книготорговцы",
    "isLiked": true,
    "duration": "1ч 37м",
  },
  {
    "id":"7",
    "link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJD2B8pKHHWNkwyixPxPhKHAWxzXbNYaBkA&usqp=CAU",
    "name": "Когда я думаю о Германии ночью",
    "isLiked": false,
    "duration": "1ч 56м",
  },
  {
    "id":"8",
    "link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJD2B8pKHHWNkwyixPxPhKHAWxzXbNYaBkA&usqp=CAU",
    "name": "Gimme Danger: История Игги и The Stooge...",
    "isLiked": false,
    "duration": "1ч 59м",
  },
  {
    "id":"9",
    "link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJD2B8pKHHWNkwyixPxPhKHAWxzXbNYaBkA&usqp=CAU",
    "name": "Дженис: Маленькая девочка грустит",
    "isLiked": true,
    "duration": "1ч 42м",
  },
  {
    "id":"10",
    "link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJD2B8pKHHWNkwyixPxPhKHAWxzXbNYaBkA&usqp=CAU",
    "name": "Соберись перед прыжком",
    "isLiked": false,
    "duration": "1ч 10м",
  },
  {
    "id":"11",
    "link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJD2B8pKHHWNkwyixPxPhKHAWxzXbNYaBkA&usqp=CAU",
    "name": "Пи Джей Харви: A dog called money",
    "isLiked": false,
    "duration": "1ч 4м",
  },
  {
    "id":"12",
    "link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJD2B8pKHHWNkwyixPxPhKHAWxzXbNYaBkA&usqp=CAU",
    "name": "По волнам: Искусство звука в кино",
    "isLiked": false,
    "duration": "1ч 7м",
  },
  {
    "id":"13",
    "link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJD2B8pKHHWNkwyixPxPhKHAWxzXbNYaBkA&usqp=CAU",
    "name": "33 слова о дизайне",
    "isLiked": true,
    "duration": "1ч 47м",
  },
  {
    "id":"14",
    "link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJD2B8pKHHWNkwyixPxPhKHAWxzXbNYaBkA&usqp=CAU",
    "name": "Киноальманах «100 лет дизайна»",
    "isLiked": false,
    "duration": "1ч 3м",
  },
  {
    "id":"15",
    "link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJD2B8pKHHWNkwyixPxPhKHAWxzXbNYaBkA&usqp=CAU",
    "name": "В погоне за Бенкси",
    "isLiked": false,
    "duration": "1ч 42м",
  },
  {
    "id":"16",
    "link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJD2B8pKHHWNkwyixPxPhKHAWxzXbNYaBkA&usqp=CAU",
    "name": "Баския: Взрыв реальности",
    "isLiked": false,
    "duration": "1ч 21м",
  },
];

